#!/bin/sh
# kFreeBSD do not accept scripts as interpreters, using #!/bin/sh and sourcing.
if [ true != "$INIT_D_SCRIPT_SOURCED" ] ; then
    set "$0" "$@"; INIT_D_SCRIPT_SOURCED=true . /lib/init/init-d-script
fi
### BEGIN INIT INFO
# Provides:          pythonWebServer
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Example initscript
# Description:       This file should be used to construct scripts to be
#                    placed in /etc/init.d.  This example start a
#                    single forking daemon capable of writing a pid
#                    file.  To get other behavoirs, implemend
#                    do_start(), do_stop() or other functions to
#                    override the defaults in /lib/init/init-d-script.
### END INIT INFO

# Author: Foo Bar <foobar@baz.org>
#
# Please remove the "Author" lines above and replace them
# with your own name if you copy and modify this script.

PROG="pythonWebServer"
RETVAL=0

start() {
	/home/pi/Server/init/verifyLaunching.sh
	EXISTS=$?
	if [ "$EXISTS"  -eq "1" ]
	then
		echo "Starting $PROG:"
		NOW=$(date +"%Y_%m_%d_%H_%M_%S") && cd /home/pi/Server/ && sudo -u pi python ./pythonWebServer.py >> ./log/log_$NOW.log&
		RETVAL=$?
		[ "$RETVAL" = 0 ] && sudo  touch /var/lock/subsys/$PROG
	else
		echo "$PROG is Alreay working"
	fi
	echo
}

stop() {	
	echo "Stopping $PROG:"

	killproc $PROG -TERM
	RETVAL=$?
	[ "$RETVAL" = 0 ] && sudo rm -f /var/lock/subsys/$PROG
	echo
}

reload() {	
	echo "Reloading $PROG:"
	killproc $PROG -HUP
	RETVAL=$?
	echo
}

case "$1" in	
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		stop
		start
		;;
	reload)
		reload
		;;
	condrestart)
		if [ -f /var/lock/subsys/$PROG ] ; then
			stop
			# avoid race
			sleep 3
			start
		fi
		;;
	status)
		status $PROG
		RETVAL=$?
		;;
	*)	
		echo "Usage: $0 {start|stop|restart|reload|condrestart|status}"
		RETVAL=1
esac
exit $RETVAL
